spring:
  application:
    name: carrierService
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    enabled: false
