package com.bhagwat.scm.carrierService.enums;
public enum MilestoneType { BOOKING_CONFIRMED, VEHICLE_ASSIGNED, PICKED, LOADED, DEPARTED_ORIGIN, IN_TRANSIT, REACHED_HUB, DEPARTED_HUB, OUT_FOR_DELIVERY, DELIVERED, DELIVERY_FAILED, RETURNED_TO_ORIGIN }
