-- Carrier master
CREATE TABLE carrier_master (
    carrier_id    VARCHAR(255) PRIMARY KEY,
    carrier_name  VARCHAR(255) NOT NULL,
    carrier_type  VARCHAR(30)  CHECK (carrier_type IN ('ROAD','RAIL','AIR','SEA','MULTI_MODAL')),
    scac_code     VARCHAR(10),
    gstin         VARCHAR(20),
    pan_number    VARCHAR(15),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(30),
    addr_street   VARCHAR(255),
    addr_city     VARCHAR(255),
    addr_state    VARCHAR(255),
    addr_country  VARCHAR(255),
    addr_pincode  VARCHAR(255),
    addr_location_id VARCHAR(255),
    active        BOOLEAN,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6)
);

-- Carrier vehicles
CREATE TABLE carrier_vehicles (
    vehicle_id         VARCHAR(255) PRIMARY KEY,
    carrier_id         VARCHAR(100) NOT NULL,
    vehicle_number     VARCHAR(30)  NOT NULL,
    vehicle_type       VARCHAR(30)  CHECK (vehicle_type IN ('TRUCK','MINI_TRUCK','VAN','BIKE','TEMPO','CONTAINER_TRUCK','REFRIGERATED_TRUCK')),
    capacity_kg        NUMERIC(10,2),
    volume_capacity_cbm NUMERIC(10,3),
    driver_name        VARCHAR(255),
    driver_phone       VARCHAR(30),
    driver_license     VARCHAR(50),
    status             VARCHAR(20)  CHECK (status IN ('AVAILABLE','ON_TRIP','MAINTENANCE','INACTIVE')),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6)
);

-- Carrier service areas
CREATE TABLE carrier_service_areas (
    id                  VARCHAR(255) PRIMARY KEY,
    carrier_id          VARCHAR(100) NOT NULL,
    carrier_name        VARCHAR(255),
    service_type        VARCHAR(20)  NOT NULL CHECK (service_type IN ('LAST_MILE','FIRST_MILE','MID_MILE','FULL_SERVICE')),
    cluster_prefix      VARCHAR(3),
    origin_cluster      VARCHAR(3),
    destination_cluster VARCHAR(3),
    city                VARCHAR(100),
    state               VARCHAR(100),
    flat_rate           NUMERIC(10,2),
    rate_per_kg         NUMERIC(10,2),
    max_weight_kg       NUMERIC(10,2),
    estimated_days      INTEGER,
    active              BOOLEAN,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6)
);

CREATE INDEX idx_csa_carrier      ON carrier_service_areas (carrier_id);
CREATE INDEX idx_csa_service_type ON carrier_service_areas (service_type);
CREATE INDEX idx_csa_cluster_type ON carrier_service_areas (cluster_prefix, service_type);

-- Carrier booking requests
CREATE TABLE carrier_booking_requests (
    cbr_id                   VARCHAR(255) PRIMARY KEY,
    cbr_number               VARCHAR(30)  NOT NULL,
    status                   VARCHAR(20)  NOT NULL CHECK (status IN ('DRAFT','BROADCAST','RESPONDED','ACCEPTED','CANCELLED')),
    shipment_type            VARCHAR(30)  CHECK (shipment_type IN ('ORDER_TO_SITE','ORDER_TO_STORE','DEMAND_ORDER','COMMUNITY_ORDER','CUSTOMER_ORDER')),
    load_type                VARCHAR(20)  CHECK (load_type IN ('FTL','HALF_TRUCK','LTL')),
    contract_id              VARCHAR(100),
    requested_by_party_id    VARCHAR(100),
    requested_by_party_name  VARCHAR(255),
    requested_by_party_type  VARCHAR(30),
    orig_street              VARCHAR(255),
    orig_city                VARCHAR(255),
    orig_state               VARCHAR(255),
    orig_country             VARCHAR(255),
    orig_pincode             VARCHAR(255),
    orig_location_id         VARCHAR(255),
    dest_street              VARCHAR(255),
    dest_city                VARCHAR(255),
    dest_state               VARCHAR(255),
    dest_country             VARCHAR(255),
    dest_pincode             VARCHAR(255),
    dest_location_id         VARCHAR(255),
    cargo_ready_date         DATE,
    requested_pickup_date    DATE,
    requested_delivery_date  DATE,
    total_packages           INTEGER,
    total_weight_kg          NUMERIC(12,3),
    total_volume_m3          NUMERIC(12,4),
    special_instructions     TEXT,
    broadcasted_at           TIMESTAMP(6),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6)
);

-- Carrier booking broadcasts
CREATE TABLE carrier_booking_broadcasts (
    broadcast_id VARCHAR(255) PRIMARY KEY,
    cbr_id       VARCHAR(100) NOT NULL,
    carrier_id   VARCHAR(100) NOT NULL,
    carrier_name VARCHAR(255),
    status       VARCHAR(20)  CHECK (status IN ('SENT','RESPONDED','DECLINED','EXPIRED')),
    sent_at      TIMESTAMP(6)
);

-- Carrier booking responses
CREATE TABLE carrier_booking_responses (
    cbr_resp_id          VARCHAR(255) PRIMARY KEY,
    cbr_resp_number      VARCHAR(30)  NOT NULL,
    cbr_id               VARCHAR(100) NOT NULL,
    carrier_id           VARCHAR(100),
    carrier_name         VARCHAR(255),
    status               VARCHAR(25)  CHECK (status IN ('PENDING','ACCEPTED_BY_CARRIER','ACCEPTED_BY_SHIPPER','DECLINED','EXPIRED')),
    rate_type            VARCHAR(25)  CHECK (rate_type IN ('FTL_FIXED','PER_KG','PER_SHIPMENT')),
    rate_offered         NUMERIC(12,2),
    currency             VARCHAR(5),
    offered_pickup_date  DATE,
    offered_delivery_date DATE,
    vehicle_id           VARCHAR(100),
    notes                TEXT,
    responded_at         TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6)
);

-- Transport requests
CREATE TABLE transport_requests (
    tr_id                    VARCHAR(255) PRIMARY KEY,
    tr_number                VARCHAR(30)  NOT NULL,
    status                   VARCHAR(20)  CHECK (status IN ('PENDING','RTS_CREATED','CANCELLED')),
    shipment_type            VARCHAR(30)  CHECK (shipment_type IN ('ORDER_TO_SITE','ORDER_TO_STORE','DEMAND_ORDER','COMMUNITY_ORDER','CUSTOMER_ORDER')),
    load_type                VARCHAR(20)  CHECK (load_type IN ('FTL','HALF_TRUCK','LTL')),
    shipping_order_id        VARCHAR(100),
    shipping_order_number    VARCHAR(100),
    contract_id              VARCHAR(100),
    cbr_id                   VARCHAR(100),
    cbr_resp_id              VARCHAR(100),
    carrier_id               VARCHAR(100),
    carrier_name             VARCHAR(255),
    agreed_rate              NUMERIC(12,2),
    currency                 VARCHAR(5),
    requested_by_party_id    VARCHAR(100),
    requested_by_party_name  VARCHAR(255),
    requested_by_party_type  VARCHAR(30),
    orig_street              VARCHAR(255),
    orig_city                VARCHAR(255),
    orig_state               VARCHAR(255),
    orig_country             VARCHAR(255),
    orig_pincode             VARCHAR(255),
    orig_location_id         VARCHAR(255),
    dest_street              VARCHAR(255),
    dest_city                VARCHAR(255),
    dest_state               VARCHAR(255),
    dest_country             VARCHAR(255),
    dest_pincode             VARCHAR(255),
    dest_location_id         VARCHAR(255),
    cargo_ready_date         DATE,
    requested_pickup_date    DATE,
    requested_delivery_date  DATE,
    total_packages           INTEGER,
    total_weight_kg          NUMERIC(12,3),
    total_volume_m3          NUMERIC(12,4),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6)
);

-- Transport request items
CREATE TABLE transport_request_items (
    item_id             VARCHAR(255) PRIMARY KEY,
    tr_id               VARCHAR(100) NOT NULL,
    order_number        VARCHAR(100),
    order_line_id       VARCHAR(100),
    product_id          VARCHAR(100),
    product_name        VARCHAR(255),
    sku_id              VARCHAR(100),
    variant_name        VARCHAR(255),
    ordered_quantity    NUMERIC(12,3),
    packed_quantity     NUMERIC(12,3),
    package_quantity    INTEGER,
    weight_kg_per_unit  NUMERIC(10,4),
    volume_m3_per_unit  NUMERIC(10,5),
    is_hazardous        BOOLEAN
);

-- Ready to ship orders
CREATE TABLE ready_to_ship_orders (
    rts_id                   VARCHAR(255) PRIMARY KEY,
    rts_number               VARCHAR(30)  NOT NULL,
    status                   VARCHAR(20)  CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','CANCELLED')),
    shipment_type            VARCHAR(30)  CHECK (shipment_type IN ('ORDER_TO_SITE','ORDER_TO_STORE','DEMAND_ORDER','COMMUNITY_ORDER','CUSTOMER_ORDER')),
    load_type                VARCHAR(20)  CHECK (load_type IN ('FTL','HALF_TRUCK','LTL')),
    incoterm                 VARCHAR(10),
    freight_payment_code     VARCHAR(20),
    tr_id                    VARCHAR(100),
    cbr_id                   VARCHAR(100),
    carrier_id               VARCHAR(100),
    carrier_name             VARCHAR(255),
    shp_party_id             VARCHAR(255),
    shp_party_name           VARCHAR(255),
    shp_party_type           VARCHAR(255),
    shp_org_id               VARCHAR(255),
    shp_contact_phone        VARCHAR(255),
    con_party_id             VARCHAR(255),
    con_party_name           VARCHAR(255),
    con_party_type           VARCHAR(255),
    con_org_id               VARCHAR(255),
    con_contact_phone        VARCHAR(255),
    orig_street              VARCHAR(255),
    orig_city                VARCHAR(255),
    orig_state               VARCHAR(255),
    orig_country             VARCHAR(255),
    orig_pincode             VARCHAR(255),
    orig_location_id         VARCHAR(255),
    dest_street              VARCHAR(255),
    dest_city                VARCHAR(255),
    dest_state               VARCHAR(255),
    dest_country             VARCHAR(255),
    dest_pincode             VARCHAR(255),
    dest_location_id         VARCHAR(255),
    cargo_ready_date_time    TIMESTAMP(6),
    cargo_cutoff_date_time   TIMESTAMP(6),
    document_cutoff_date_time TIMESTAMP(6),
    total_packages           INTEGER,
    total_weight_kg          NUMERIC(12,3),
    total_volume_m3          NUMERIC(12,4),
    asn_sent                 BOOLEAN,
    asn_sent_at              TIMESTAMP(6),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6)
);

-- Ready to ship items
CREATE TABLE ready_to_ship_items (
    rts_item_id         VARCHAR(255) PRIMARY KEY,
    rts_id              VARCHAR(100) NOT NULL,
    order_number        VARCHAR(100),
    order_line_id       VARCHAR(100),
    product_id          VARCHAR(100),
    product_name        VARCHAR(255),
    sku_id              VARCHAR(100),
    variant_name        VARCHAR(255),
    ordered_quantity    NUMERIC(12,3),
    packed_quantity     NUMERIC(12,3),
    package_quantity    INTEGER,
    weight_kg_per_unit  NUMERIC(10,4),
    volume_m3_per_unit  NUMERIC(10,5),
    is_hazardous        BOOLEAN
);

-- Advanced shipment notices
CREATE TABLE advanced_shipment_notices (
    asn_id              VARCHAR(255) PRIMARY KEY,
    asn_number          VARCHAR(30)  NOT NULL,
    status              VARCHAR(20)  CHECK (status IN ('SENT','ACKNOWLEDGED','RECEIVED')),
    shipment_type       VARCHAR(30)  CHECK (shipment_type IN ('ORDER_TO_SITE','ORDER_TO_STORE','DEMAND_ORDER','COMMUNITY_ORDER','CUSTOMER_ORDER')),
    rts_id              VARCHAR(100),
    rts_number          VARCHAR(30),
    carrier_id          VARCHAR(100),
    carrier_name        VARCHAR(255),
    sent_to_party_id    VARCHAR(100),
    sent_to_party_name  VARCHAR(255),
    sent_to_party_type  VARCHAR(30),
    orig_street         VARCHAR(255),
    orig_city           VARCHAR(255),
    orig_state          VARCHAR(255),
    orig_country        VARCHAR(255),
    orig_pincode        VARCHAR(255),
    orig_location_id    VARCHAR(255),
    dest_street         VARCHAR(255),
    dest_city           VARCHAR(255),
    dest_state          VARCHAR(255),
    dest_country        VARCHAR(255),
    dest_pincode        VARCHAR(255),
    dest_location_id    VARCHAR(255),
    expected_arrival_date DATE,
    delivery_window     VARCHAR(20),
    total_packages      INTEGER,
    total_weight_kg     NUMERIC(12,3),
    total_volume_m3     NUMERIC(12,4),
    sent_at             TIMESTAMP(6),
    acknowledged_at     TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6)
);

-- Transport shipments
CREATE TABLE transport_shipments (
    ts_id                        VARCHAR(255) PRIMARY KEY,
    ts_number                    VARCHAR(30)  NOT NULL,
    status                       VARCHAR(25)  CHECK (status IN ('CREATED','PICKED','SHIPPED','IN_TRANSIT','REACHED_HUB','OUT_FOR_DELIVERY','DELIVERED','DELIVERY_FAILED','RETURNED')),
    shipment_type                VARCHAR(30)  CHECK (shipment_type IN ('ORDER_TO_SITE','ORDER_TO_STORE','DEMAND_ORDER','COMMUNITY_ORDER','CUSTOMER_ORDER')),
    rts_id                       VARCHAR(100),
    rts_number                   VARCHAR(30),
    transport_plan_id            VARCHAR(100),
    transport_plan_number        VARCHAR(30),
    carrier_id                   VARCHAR(100),
    carrier_name                 VARCHAR(255),
    vehicle_id                   VARCHAR(100),
    vehicle_number               VARCHAR(30),
    driver_name                  VARCHAR(255),
    driver_phone                 VARCHAR(30),
    shp_party_id                 VARCHAR(255),
    shp_party_name               VARCHAR(255),
    shp_party_type               VARCHAR(255),
    shp_org_id                   VARCHAR(255),
    shp_contact_phone            VARCHAR(255),
    con_party_id                 VARCHAR(255),
    con_party_name               VARCHAR(255),
    con_party_type               VARCHAR(255),
    con_org_id                   VARCHAR(255),
    con_contact_phone            VARCHAR(255),
    orig_street                  VARCHAR(255),
    orig_city                    VARCHAR(255),
    orig_state                   VARCHAR(255),
    orig_country                 VARCHAR(255),
    orig_pincode                 VARCHAR(255),
    orig_location_id             VARCHAR(255),
    dest_street                  VARCHAR(255),
    dest_city                    VARCHAR(255),
    dest_state                   VARCHAR(255),
    dest_country                 VARCHAR(255),
    dest_pincode                 VARCHAR(255),
    dest_location_id             VARCHAR(255),
    current_location             VARCHAR(255),
    estimated_delivery_date_time TIMESTAMP(6),
    actual_pickup_date_time      TIMESTAMP(6),
    actual_delivery_date_time    TIMESTAMP(6),
    failure_reason               TEXT,
    total_packages               INTEGER,
    total_weight_kg              NUMERIC(12,3),
    total_volume_m3              NUMERIC(12,4),
    created_at                   TIMESTAMP(6) NOT NULL,
    updated_at                   TIMESTAMP(6)
);

-- Shipment milestones
CREATE TABLE shipment_milestones (
    milestone_id        VARCHAR(255) PRIMARY KEY,
    ts_id               VARCHAR(100) NOT NULL,
    milestone_type      VARCHAR(30)  NOT NULL CHECK (milestone_type IN ('BOOKING_CONFIRMED','VEHICLE_ASSIGNED','PICKED','LOADED','DEPARTED_ORIGIN','IN_TRANSIT','REACHED_HUB','DEPARTED_HUB','OUT_FOR_DELIVERY','DELIVERED','DELIVERY_FAILED','RETURNED_TO_ORIGIN')),
    milestone_date_time TIMESTAMP(6) NOT NULL,
    location            VARCHAR(255),
    latitude            NUMERIC(10,6),
    longitude           NUMERIC(10,6),
    notes               TEXT,
    posted_by           VARCHAR(255),
    created_at          TIMESTAMP(6) NOT NULL
);
